/**
 * Simulation — "advance the data cycle" state.
 *
 * One button in the TopBar advances mock time: every monitored project's
 * risk inputs drift deterministically (delays lengthen, gaps widen — one
 * project improves), scores move everywhere the engine is used, and fresh
 * cycle events flow into the Official's alert feed. Pure client-side; a
 * reload returns to the live cycle.
 *
 * Deterministic by (cycle, project index) — no randomness, so every viewer
 * sees the same story during a demo.
 */
import {
  createContext,
  useContext,
  useMemo,
  useState,
  type ReactNode,
} from 'react';
import { monitoredProjects, type MonitoredProject } from '../data/projects';
import { createRuleEngine } from '../engine';
import type { PlotRiskInput } from '../engine/types';

const engine = createRuleEngine();

/** One new alert produced by a simulated cycle. */
export interface CycleEvent {
  id: string;
  cycle: number;
  projectId: string;
  projectName: string;
  event: string;
  severity: 'High' | 'Medium' | 'Low';
  ago: string;
}

interface SimulationStore {
  /** 0 = live data; 1+ = simulated cycles ahead. */
  cycle: number;
  /** Projects with cycle-adjusted risk inputs (base data otherwise intact). */
  projects: MonitoredProject[];
  /** Events generated by advancing cycles, newest first. */
  events: CycleEvent[];
  /** Advance one cycle. */
  advance: () => void;
  /** Return to the live cycle (cycle 0, no events). */
  reset: () => void;
}

/** Deterministic drift for one project after `cycle` elapsed cycles. */
function driftInput(project: MonitoredProject, cycle: number): PlotRiskInput {
  if (cycle === 0) return project.riskInput;
  const i = monitoredProjects.findIndex((p) => p.id === project.id);
  const base = project.riskInput;

  // Musi central stretch (index 3) is the improving story: gaps narrow.
  const improving = project.id === 'LAP-2022-032';
  const gapStep = improving ? -6 : i % 2 === 0 ? 12 : 9;
  const rrStep = improving ? -10 : 25;

  return {
    ...base,
    compensationGapPct: Math.max(
      0,
      Math.min(95, base.compensationGapPct + gapStep * cycle),
    ),
    approvalDelayDays: improving
      ? base.approvalDelayDays
      : base.approvalDelayDays + 21 * cycle,
    rrFamiliesAwaitingResettlement: Math.max(
      0,
      base.rrFamiliesAwaitingResettlement + rrStep * cycle,
    ),
  };
}

/** Projects re-derived for a given cycle (pure). */
function simulate(projects: MonitoredProject[], cycle: number): MonitoredProject[] {
  if (cycle === 0) return projects;
  return projects.map((p) => ({ ...p, riskInput: driftInput(p, cycle) }));
}

/** Events for advancing from cycle-1 → cycle: the biggest movers. */
function eventsForCycle(cycle: number, projects: MonitoredProject[]): CycleEvent[] {
  const scored = projects.map((p) => ({
    p,
    r: engine.predict(driftInput(p, cycle)),
    prev: engine.predict(driftInput(p, cycle - 1)),
  }));
  const movers = scored
    .map((s) => ({ ...s, delta: s.r.score - s.prev.score }))
    .sort((a, b) => Math.abs(b.delta) - Math.abs(a.delta))
    .slice(0, 3);

  return movers.map((m, i) => {
    const crossed =
      m.prev.level !== m.r.level
        ? ` — crossing into ${m.r.level} risk`
        : '';
    const direction = m.delta >= 0 ? 'rose' : 'eased';
    return {
      id: `CY-${cycle}-${i}`,
      cycle,
      projectId: m.p.id,
      projectName: m.p.name,
      event: `Cycle ${cycle}: risk score ${direction} ${m.prev.score} → ${m.r.score}${crossed}`,
      severity: m.r.level,
      ago: `Cycle ${cycle} · just now`,
    };
  });
}

const SimulationContext = createContext<SimulationStore | null>(null);

export function SimulationProvider({ children }: { children: ReactNode }) {
  const [cycle, setCycle] = useState(0);
  const [events, setEvents] = useState<CycleEvent[]>([]);

  const store = useMemo<SimulationStore>(() => {
    const projects = simulate(monitoredProjects, cycle);
    return {
      cycle,
      projects,
      events: [...events].sort((a, b) => b.cycle - a.cycle),
      advance: () => {
        const next = cycle + 1;
        setCycle(next);
        setEvents((prev) => [...eventsForCycle(next, monitoredProjects), ...prev]);
      },
      reset: () => {
        setCycle(0);
        setEvents([]);
      },
    };
  }, [cycle, events]);

  return (
    <SimulationContext.Provider value={store}>
      {children}
    </SimulationContext.Provider>
  );
}

/** Simulation state — throws outside the provider (mounted at App root). */
export function useSimulation(): SimulationStore {
  const ctx = useContext(SimulationContext);
  if (!ctx) {
    throw new Error('useSimulation must be used inside <SimulationProvider>');
  }
  return ctx;
}
